sudo: required
dist: trusty
language: node_js
node_js:
- stable
services:
- docker
notifications:
  email:
    recipients:
    - tiringerdaniel@gmail.com
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - development

services:
  -docker

before_script:
  npm install

script:
  npm run test

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run build;

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;

    export REPO=danieltiringer/maintenance-program;
    docker build -f Dockerfile -t $REPO .;
    docker push $REPO;
  fi
